language: php

git:
    depth: 1

sudo: false

matrix:
    fast_finish: true
    include:
        - php: 5.4
          env: MEMCACHED_PECL=memcached-1.0.2 COMPOSER_FLAGS="--prefer-stable --prefer-lowest"
        - php: 5.5
          env: MEMCACHED_PECL=memcached-2.0.1 COMPOSER_FLAGS="--prefer-stable"
        - php: 5.6
          env: MEMCACHED_PECL=memcached-2.1.0 COMPOSER_FLAGS="--prefer-stable"
        - php: 7.0
          env: MEMCACHED_PECL=memcached-2.2.0 COMPOSER_FLAGS="--prefer-stable"
        - php: 7.1
          env: MEMCACHED_PECL=memcached-2.2.0 COMPOSER_FLAGS="--dev"
        - php: hhvm-3.9
          sudo: required
          dist: trusty
          group: edge
          env: COMPOSER_FLAGS="--prefer-stable"
        - php: hhvm-nightly
          sudo: required
          dist: trusty
          group: edge
          env: COMPOSER_FLAGS="--dev"
    allow_failures:
        - php: hhvm-nightly

before_install:
    - if [[ ! $TRAVIS_PHP_VERSION = hhvm* ]]; then yes "" | pecl install -f "$MEMCACHED_PECL"; fi

install:
    - composer update $COMPOSER_FLAGS --no-interaction -v
    - if [[ $TRAVIS_PHP_VERSION = 7.0 ]]; then curl -L https://github.com/FriendsOfPHP/PHP-CS-Fixer/releases/download/v1.13.0/php-cs-fixer.phar -o php-cs-fixer.phar; fi

script:
    - phpunit --verbose
    - if [[ $TRAVIS_PHP_VERSION = 7.0 ]]; then php php-cs-fixer.phar --dry-run -vvv fix; fi
