language: php

git:
    depth: 1

sudo: false

matrix:
    fast_finish: true
    include:
        - php: 5.4
          env: MEMCACHED_PECL=memcached-1.0.2 COMPOSER_FLAGS="--prefer-stable --prefer-lowest"
        - php: 5.5
          env: MEMCACHED_PECL=memcached-2.0.1 COMPOSER_FLAGS="--prefer-stable"
        - php: 5.6
          env: MEMCACHED_PECL=memcached-2.1.0 COMPOSER_FLAGS="--prefer-stable"
        - php: 7.0
          env: MEMCACHED_PECL=memcached-2.2.0 COMPOSER_FLAGS="--prefer-stable"
        - php: 7.1
          env: MEMCACHED_PECL=memcached-2.2.0 COMPOSER_FLAGS="--dev"
        - php: 7.2
          env: MEMCACHED_PECL=memcached-2.2.0 COMPOSER_FLAGS="--dev"
        - php: nightly
          env: MEMCACHED_PECL=memcached-2.2.0 COMPOSER_FLAGS="--dev"

before_install:
    - yes "" | pecl install -f "$MEMCACHED_PECL";

install:
    - travis_retry composer update $COMPOSER_FLAGS --no-interaction -v
    - composer info -D | sort
    - if [[ $TRAVIS_PHP_VERSION = 7.0 ]]; then curl -L https://github.com/FriendsOfPHP/PHP-CS-Fixer/releases/download/v1.13.0/php-cs-fixer.phar -o php-cs-fixer.phar; fi

script:
    - phpenv config-rm xdebug.ini || return 0
    - phpunit --verbose
    - if [[ $TRAVIS_PHP_VERSION = 7.0 ]]; then php php-cs-fixer.phar --dry-run -vvv fix; fi
